# Generated by Django 4.2.30 on 2026-08-24 03:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ops', '0066_llm_provider_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrpAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, help_text='数据库主键。', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='记录创建时间。')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新时间。')),
                ('agent_id', models.CharField(help_text='frp agent的Agent ID字段。', max_length=160, verbose_name='Agent ID')),
                ('fingerprint', models.CharField(help_text='frp agent的机器指纹字段。', max_length=128, verbose_name='机器指纹')),
                ('hostname', models.CharField(blank=True, help_text='frp agent的主机名字段。', max_length=160, verbose_name='主机名')),
                ('management_ip', models.GenericIPAddressField(blank=True, help_text='frp agent的管理 IP字段。', null=True, verbose_name='管理 IP')),
                ('client_ip', models.GenericIPAddressField(blank=True, help_text='发起会话的客户端 IP 地址。', null=True, verbose_name='注册来源 IP')),
                ('os', models.CharField(blank=True, help_text='frp agent的操作系统字段。', max_length=80, verbose_name='操作系统')),
                ('arch', models.CharField(blank=True, help_text='frp agent的架构字段。', max_length=80, verbose_name='架构')),
                ('version', models.CharField(blank=True, help_text='frp agent的Agent 版本字段。', max_length=80, verbose_name='Agent 版本')),
                ('username', models.CharField(blank=True, help_text='登录目标系统使用的用户名。', max_length=120, verbose_name='运行用户')),
                ('source', models.CharField(choices=[('manual', '手动维护'), ('frps_dashboard', 'frps Dashboard'), ('agent_report', 'Agent 上报')], default='manual', help_text='frp agent的来源字段。', max_length=32, verbose_name='来源')),
                ('admin_host', models.CharField(blank=True, help_text='frp agent的frpc Admin API 地址字段。', max_length=180, verbose_name='frpc Admin API 地址')),
                ('admin_port', models.PositiveIntegerField(blank=True, help_text='frp agent的frpc Admin API 端口字段。', null=True, verbose_name='frpc Admin API 端口')),
                ('admin_username', models.CharField(blank=True, help_text='frp agent的frpc Admin API 用户名字段。', max_length=120, verbose_name='frpc Admin API 用户名')),
                ('encrypted_admin_password', models.TextField(blank=True, help_text='frp agent的frpc Admin API 密码密文字段。', verbose_name='frpc Admin API 密码密文')),
                ('admin_proxy_name', models.CharField(blank=True, help_text='frp agent的frpc 管理隧道名称字段。', max_length=160, verbose_name='frpc 管理隧道名称')),
                ('admin_proxy_remote_addr', models.CharField(blank=True, help_text='frp agent的frpc 管理隧道远端地址字段。', max_length=240, verbose_name='frpc 管理隧道远端地址')),
                ('store_enabled', models.BooleanField(default=False, help_text='frp agent的frpc Store API 已启用字段。', verbose_name='frpc Store API 已启用')),
                ('runtime_proxy_count', models.PositiveIntegerField(default=0, help_text='frp agent的运行隧道数量字段。', verbose_name='运行隧道数量')),
                ('tags', models.JSONField(blank=True, default=list, help_text='frp agent的标签字段。', verbose_name='标签')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='frp agent的上报元数据字段。', verbose_name='上报元数据')),
                ('approval_status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', help_text='frp agent的审核状态字段。', max_length=32, verbose_name='审核状态')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('unavailable', '异常'), ('disabled', '已禁用')], default='offline', help_text='记录当前业务状态。', max_length=32, verbose_name='在线状态')),
                ('last_heartbeat_at', models.DateTimeField(blank=True, help_text='frp agent的最近心跳时间字段。', null=True, verbose_name='最近心跳时间')),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='frp agent的最近上报时间字段。', null=True, verbose_name='最近上报时间')),
                ('last_error', models.CharField(blank=True, help_text='最近一次录像处理错误说明。', max_length=240, verbose_name='最近错误')),
                ('approved_by', models.CharField(blank=True, help_text='frp agent的审核人字段。', max_length=120, verbose_name='审核人')),
                ('approved_at', models.DateTimeField(blank=True, help_text='审批节点处理完成时间。', null=True, verbose_name='审核时间')),
                ('rejected_by', models.CharField(blank=True, help_text='frp agent的拒绝人字段。', max_length=120, verbose_name='拒绝人')),
                ('rejected_at', models.DateTimeField(blank=True, help_text='frp agent的拒绝时间字段。', null=True, verbose_name='拒绝时间')),
                ('reject_reason', models.CharField(blank=True, help_text='frp agent的拒绝原因字段。', max_length=240, verbose_name='拒绝原因')),
                ('remark', models.TextField(blank=True, help_text='业务备注信息。', verbose_name='备注')),
                ('organization', models.ForeignKey(blank=True, help_text='记录所属组织，用于数据隔离。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frp_agents', to='ops.organization', verbose_name='组织')),
            ],
            options={
                'ordering': ['-last_seen_at', 'hostname'],
            },
        ),
        migrations.CreateModel(
            name='FrpServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, help_text='数据库主键。', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='记录创建时间。')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新时间。')),
                ('name', models.CharField(help_text='记录的显示名称。', max_length=120, verbose_name='服务端名称')),
                ('server_code', models.SlugField(help_text='frp server的服务端编码字段。', max_length=120, verbose_name='服务端编码')),
                ('public_host', models.CharField(help_text='frp server的公网地址字段。', max_length=180, verbose_name='公网地址')),
                ('bind_port', models.PositiveIntegerField(default=7000, help_text='frp server的FRP 服务端端口字段。', verbose_name='FRP 服务端端口')),
                ('allow_ports', models.CharField(blank=True, help_text='frp server的允许映射端口范围字段。', max_length=240, verbose_name='允许映射端口范围')),
                ('dashboard_host', models.CharField(blank=True, help_text='frp server的Dashboard 地址字段。', max_length=180, verbose_name='Dashboard 地址')),
                ('dashboard_port', models.PositiveIntegerField(default=7500, help_text='frp server的Dashboard 端口字段。', verbose_name='Dashboard 端口')),
                ('dashboard_username', models.CharField(blank=True, help_text='frp server的Dashboard 用户名字段。', max_length=120, verbose_name='Dashboard 用户名')),
                ('encrypted_dashboard_password', models.TextField(blank=True, help_text='frp server的Dashboard 密码密文字段。', verbose_name='Dashboard 密码密文')),
                ('encrypted_auth_token', models.TextField(blank=True, help_text='frp server的FRP 认证 Token 密文字段。', verbose_name='FRP 认证 Token 密文')),
                ('client_admin_username', models.CharField(blank=True, default='cmdb', help_text='frp server的frpc Admin API 用户名字段。', max_length=120, verbose_name='frpc Admin API 用户名')),
                ('encrypted_client_admin_password', models.TextField(blank=True, help_text='frp server的frpc Admin API 密码密文字段。', verbose_name='frpc Admin API 密码密文')),
                ('allow_register', models.BooleanField(default=True, help_text='frp server的允许 Agent 注册字段。', verbose_name='允许 Agent 注册')),
                ('max_agents', models.PositiveIntegerField(default=200, help_text='frp server的最大接入数量字段。', verbose_name='最大接入数量')),
                ('status', models.CharField(choices=[('available', '可用'), ('configured', '已配置'), ('unconfigured', '未配置'), ('unavailable', '不可用'), ('disabled', '已禁用')], default='configured', help_text='记录当前业务状态。', max_length=32, verbose_name='状态')),
                ('last_test_status', models.CharField(choices=[('not_tested', '未测试'), ('success', '测试成功'), ('failed', '测试失败')], default='not_tested', help_text='最近一次账号连接测试状态。', max_length=32, verbose_name='最近测试状态')),
                ('last_test_message', models.CharField(blank=True, help_text='最近一次账号连接测试说明。', max_length=240, verbose_name='最近测试结果')),
                ('last_test_at', models.DateTimeField(blank=True, help_text='frp server的最近测试时间字段。', null=True, verbose_name='最近测试时间')),
                ('remark', models.TextField(blank=True, help_text='业务备注信息。', verbose_name='备注')),
                ('organization', models.ForeignKey(blank=True, help_text='记录所属组织，用于数据隔离。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frp_servers', to='ops.organization', verbose_name='组织')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FrpProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, help_text='数据库主键。', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='记录创建时间。')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新时间。')),
                ('name', models.CharField(help_text='记录的显示名称。', max_length=120, verbose_name='代理名称')),
                ('proxy_type', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP'), ('http', 'HTTP'), ('https', 'HTTPS'), ('stcp', 'STCP'), ('xtcp', 'XTCP')], default='tcp', help_text='frp proxy的代理类型字段。', max_length=16, verbose_name='代理类型')),
                ('local_ip', models.CharField(default='127.0.0.1', help_text='frp proxy的本地地址字段。', max_length=120, verbose_name='本地地址')),
                ('local_port', models.PositiveIntegerField(default=22, help_text='frp proxy的本地端口字段。', verbose_name='本地端口')),
                ('remote_port', models.PositiveIntegerField(blank=True, help_text='frp proxy的远端端口字段。', null=True, verbose_name='远端端口')),
                ('custom_domains', models.JSONField(blank=True, default=list, help_text='frp proxy的自定义域名字段。', verbose_name='自定义域名')),
                ('subdomain', models.CharField(blank=True, help_text='frp proxy的子域名字段。', max_length=120, verbose_name='子域名')),
                ('status', models.CharField(choices=[('available', '可用'), ('configured', '已配置'), ('unavailable', '不可用'), ('disabled', '已禁用')], default='configured', help_text='记录当前业务状态。', max_length=32, verbose_name='状态')),
                ('last_test_status', models.CharField(choices=[('not_tested', '未测试'), ('success', '测试成功'), ('failed', '测试失败')], default='not_tested', help_text='最近一次账号连接测试状态。', max_length=32, verbose_name='最近测试状态')),
                ('last_test_message', models.CharField(blank=True, help_text='最近一次账号连接测试说明。', max_length=240, verbose_name='最近测试结果')),
                ('last_test_at', models.DateTimeField(blank=True, help_text='frp proxy的最近测试时间字段。', null=True, verbose_name='最近测试时间')),
                ('remark', models.TextField(blank=True, help_text='业务备注信息。', verbose_name='备注')),
                ('agent', models.ForeignKey(help_text='frp proxy的所属 Agent字段。', on_delete=django.db.models.deletion.CASCADE, related_name='proxies', to='security_frp.frpagent', verbose_name='所属 Agent')),
                ('organization', models.ForeignKey(blank=True, help_text='记录所属组织，用于数据隔离。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frp_proxies', to='ops.organization', verbose_name='组织')),
                ('server', models.ForeignKey(help_text='frp proxy的所属服务端字段。', on_delete=django.db.models.deletion.CASCADE, related_name='proxies', to='security_frp.frpserver', verbose_name='所属服务端')),
            ],
            options={
                'ordering': ['server__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FrpAgentHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, help_text='数据库主键。', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='记录创建时间。')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新时间。')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('error', '异常')], default='online', help_text='记录当前业务状态。', max_length=32, verbose_name='状态')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='目标或客户端的 IP 地址。', null=True, verbose_name='来源 IP')),
                ('message', models.CharField(blank=True, help_text='本次处理结果或错误说明。', max_length=240, verbose_name='消息')),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='frp agent heartbeat的指标字段。', verbose_name='指标')),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now, help_text='frp agent heartbeat的上报时间字段。', verbose_name='上报时间')),
                ('agent', models.ForeignKey(help_text='frp agent heartbeat的所属 Agent字段。', on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='security_frp.frpagent', verbose_name='所属 Agent')),
                ('organization', models.ForeignKey(blank=True, help_text='记录所属组织，用于数据隔离。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frp_heartbeats', to='ops.organization', verbose_name='组织')),
                ('server', models.ForeignKey(help_text='frp agent heartbeat的所属服务端字段。', on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='security_frp.frpserver', verbose_name='所属服务端')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.AddField(
            model_name='frpagent',
            name='server',
            field=models.ForeignKey(help_text='frp agent的所属服务端字段。', on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='security_frp.frpserver', verbose_name='所属服务端'),
        ),
        migrations.AddIndex(
            model_name='frpserver',
            index=models.Index(fields=['organization', 'status'], name='frp_server_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='frpserver',
            index=models.Index(fields=['server_code'], name='frp_server_code_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='frpserver',
            unique_together={('organization', 'server_code')},
        ),
        migrations.AddIndex(
            model_name='frpproxy',
            index=models.Index(fields=['organization', 'status'], name='frp_proxy_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='frpproxy',
            index=models.Index(fields=['server', 'agent'], name='frp_proxy_server_agent_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='frpproxy',
            unique_together={('organization', 'server', 'name')},
        ),
        migrations.AddIndex(
            model_name='frpagentheartbeat',
            index=models.Index(fields=['organization', 'reported_at'], name='frp_heartbeat_org_time_idx'),
        ),
        migrations.AddIndex(
            model_name='frpagentheartbeat',
            index=models.Index(fields=['agent', 'reported_at'], name='frp_heartbeat_agent_time_idx'),
        ),
        migrations.AddIndex(
            model_name='frpagent',
            index=models.Index(fields=['organization', 'approval_status'], name='frp_agent_org_approval_idx'),
        ),
        migrations.AddIndex(
            model_name='frpagent',
            index=models.Index(fields=['organization', 'status'], name='frp_agent_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='frpagent',
            index=models.Index(fields=['fingerprint'], name='frp_agent_fingerprint_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='frpagent',
            unique_together={('organization', 'server', 'fingerprint')},
        ),
    ]
