from django.db import models


FIELD_HELP_TEXT = {
    'id': '数据库主键。',
    'created_at': '记录创建时间。',
    'updated_at': '记录最后更新时间。',
    'organization': '记录所属组织，用于数据隔离。',
    'name': '记录的显示名称。',
    'status': '记录当前业务状态。',
    'description': '记录用途和补充说明。',
    'remark': '业务备注信息。',
    'parent': '当前节点的直接上级节点。',
    'sort_order': '同级记录的展示顺序。',
    'color': '标签在页面中展示的颜色。',
    'ip_address': '目标或客户端的 IP 地址。',
    'protocol': '连接或传输使用的协议。',
    'port': '网络服务端口。',
    'platform': '目标资产的操作系统平台。',
    'group': '资产所属的目录分组。',
    'cabinet': '资产所在机柜或物理位置。',
    'maintenance_window': '资产约定的维护时间窗口。',
    'last_checked_at': '最近一次连通性检测时间。',
    'last_check_message': '最近一次连通性检测结果说明。',
    'labels': '资产关联的分类标签。',
    'asset': '关联的目标资产。',
    'checked_at': '状态检测发生时间。',
    'message': '本次处理结果或错误说明。',
    'username': '登录目标系统使用的用户名。',
    'account_type': '目标账号的认证方式。',
    'encrypted_password': '使用 SM4 加密保存的目标账号密码。',
    'encrypted_private_key': '使用 SM4 加密保存的 SSH 私钥。',
    'passphrase_encrypted': '使用 SM4 加密保存的私钥口令。',
    'privileged': '是否为具有高权限的目标账号。',
    'rotation_policy_days': '账号密码自动轮换周期天数。',
    'expires_at': '记录或凭据失效时间。',
    'last_test_status': '最近一次账号连接测试状态。',
    'last_test_message': '最近一次账号连接测试说明。',
    'last_tested_at': '最近一次账号连接测试时间。',
    'asset_group': '规则适用的资产目录。',
    'min_length': '密码允许的最小长度。',
    'require_upper': '密码是否必须包含大写字母。',
    'require_lower': '密码是否必须包含小写字母。',
    'require_number': '密码是否必须包含数字。',
    'require_symbol': '密码是否必须包含特殊符号。',
    'expire_days': '密码有效期天数。',
    'rotation_days': '密码轮换周期天数。',
    'history_count': '禁止重复使用的历史密码数量。',
    'account': '关联的目标账号。',
    'old_secret_hash': '变更前凭据的不可逆摘要。',
    'new_secret_hash': '变更后凭据的不可逆摘要。',
    'change_type': '凭据变更的触发方式。',
    'department': '规则或用户关联的部门。',
    'auto_match_account': '是否自动匹配资产上的可用账号。',
    'access_modes': '允许的连接和文件传输方式。',
    'valid_from': '授权开始生效时间。',
    'valid_until': '授权停止生效时间。',
    'time_window': '授权每天允许访问的时间范围。',
    'command_filter': '兼容历史数据的命令过滤配置。',
    'priority': '规则匹配优先级，数值越小越优先。',
    'require_approval': '操作是否必须经过审批流程。',
    'users': '规则直接授权的用户集合。',
    'assets': '规则直接授权的资产集合。',
    'command_filter_rules': '授权关联的命令过滤规则。',
    'approval_type': '审批流适用的业务类型。',
    'subject_type': '审批流或策略的授权对象类型。',
    'subject_department': '审批流适用的部门。',
    'nodes': '兼容历史数据的审批节点配置。',
    'subject_users': '审批流适用的用户集合。',
    'ticket_type': '审批单对应的业务类型。',
    'applicant': '发起审批申请的用户。',
    'related_object_type': '审批关联业务对象的类型。',
    'related_object_id': '审批关联业务对象的主键。',
    'title': '记录标题或任务名称。',
    'reason': '申请、拒绝或处理的原因。',
    'ticket': '审批节点所属的审批单。',
    'approver': '当前审批节点的处理人。',
    'sequence': '事件或审批节点的执行顺序。',
    'comment': '处理意见或补充说明。',
    'approved_at': '审批节点处理完成时间。',
    'mode': '规则采用黑名单或白名单模式。',
    'pattern': '用于匹配命令的规则表达式。',
    'block': '命中规则后是否阻断操作。',
    'user': '关联的平台用户。',
    'connector_status': '远程连接器当前状态。',
    'gateway_message': '远程网关返回的结果说明。',
    'purpose': '用户发起连接的用途说明。',
    'client_ip': '发起会话的客户端 IP 地址。',
    'started_at': '业务开始时间。',
    'ended_at': '业务结束时间。',
    'idle_timeout_minutes': '会话空闲自动断开的分钟数。',
    'clipboard_enabled': '远程会话是否允许使用剪贴板。',
    'terminal_theme': 'Web 终端使用的显示主题。',
    'display_width': '远程桌面的显示宽度像素。',
    'display_height': '远程桌面的显示高度像素。',
    'display_dpi': '远程桌面的显示分辨率。',
    'guacamole_token': 'Guacamole 连接使用的短期令牌。',
    'guacamole_connection_id': 'Guacamole 远程连接标识。',
    'guacamole_recording_name': 'Guacamole 生成的录像名称。',
    'session': '关联的堡垒机会话。',
    'file_path': '本地或对象存储中的文件位置。',
    'replay_format': '会话回放文件格式。',
    'file_size': '文件大小，单位为字节。',
    'duration_seconds': '会话或录像持续秒数。',
    'inviter': '发起会话共享的用户。',
    'invitee': '被邀请加入会话的用户。',
    'permission': '共享会话允许的操作级别。',
    'locked_by': '执行会话锁定的用户。',
    'locked_at': '会话锁定时间。',
    'unlocked_at': '会话解除锁定时间。',
    'risk_level': '命令或事件的风险等级。',
    'alert': '命中规则后是否生成风险告警。',
    'command': '用户通过会话提交的命令内容。',
    'blocked': '命令是否被安全规则阻断。',
    'result': '业务操作的处理结果。',
    'executed_at': '命令执行或拦截时间。',
    'rule': '触发告警的风险规则。',
    'command_log': '告警关联的命令审计记录。',
    'matched_command': '触发风险规则的实际命令。',
    'handled_by': '处理风险告警的用户。',
    'handled_at': '风险告警处理时间。',
    'transfer_task': '关联的文件传输任务。',
    'operation': '文件传输操作类型。',
    'source_path': '文件传输的来源路径。',
    'target_path': '文件传输的目标路径。',
    'file_hash': '文件完整性校验摘要。',
    'login_type': '平台登录或目标资产登录类型。',
    'user_agent': '客户端浏览器或程序标识。',
    'report_type': '审计报表包含的数据类型。',
    'start_at': '查询或导出的开始时间。',
    'end_at': '查询或导出的结束时间。',
    'summary': '报表的用户友好汇总数据。',
    'source_asset': '服务器间拷贝的来源资产。',
    'direction': '上传、下载或服务器间拷贝方向。',
    'total_size': '任务内全部文件的总字节数。',
    'approval_ticket': '任务关联的审批单。',
    'progress': '任务完成百分比。',
    'task': '当前记录所属的任务。',
    'item': '安全扫描对应的文件项。',
    'extension_result': '文件扩展名安全检查结果。',
    'virus_result': '病毒扫描结果。',
    'sensitive_result': '敏感文件名检查结果。',
    'allowed': '安全扫描是否允许继续传输。',
    'cleaned': '临时文件是否已完成清理。',
    'storage_backend': '录像文件使用的存储后端。',
    'recording_type': '终端流或浏览器录屏等录像类型。',
    'content_type': '录像文件的 MIME 类型。',
    'file_format': '录像或导出文件格式。',
    'oss_bucket': '对象存储桶名称。',
    'oss_endpoint': '对象存储服务地址。',
    'oss_object_key': '对象存储中的文件键。',
    'oss_url': '对象存储文件访问地址。',
    'last_error': '最近一次录像处理错误说明。',
    'recording': '事件所属的录像记录。',
    'offset_ms': '回放事件相对录像开始的毫秒偏移。',
    'event_type': '录像事件类型。',
    'payload': '终端输出或尺寸变化等事件内容。',
    'payload_size': '事件内容的字节数。',
    'oss_transfer_retention_days': 'OSS 中转文件保留天数。',
    'recording_retention_days': '会话录像保留天数。',
    'command_audit_retention_days': '命令审计记录保留天数。',
    'session_audit_retention_days': '会话审计记录保留天数。',
    'max_transfer_file_mb': '单个传输文件允许的最大 MB 数。',
    'auto_cleanup_enabled': '是否自动清理过期中转文件。',
    'delete_oss_object_on_cleanup': '清理时是否同步删除 OSS 对象。',
    'safe_scan_enabled': '是否在传输前执行文件安全扫描。',
    'blocked_extensions': '禁止传输的文件扩展名列表。',
    'allowed_extensions': '允许传输的文件扩展名白名单。',
    'export_type': '导出任务包含的业务数据类型。',
    'export_format': '导出文件格式。',
    'days': '未指定时间范围时默认导出的最近天数。',
    'row_count': '导出文件包含的数据行数。',
    'scheduled_at': '文件计划清理时间。',
    'cleaned_at': '文件实际清理完成时间。',
}


def apply_model_field_help(namespace):
    """为当前 models.py 中缺少说明的本地模型字段补齐中文 help_text。"""
    for candidate in namespace.values():
        if not isinstance(candidate, type) or not issubclass(candidate, models.Model):
            continue
        if candidate.__module__ != namespace.get('__name__'):
            continue
        for field in [*candidate._meta.local_fields, *candidate._meta.local_many_to_many]:
            if field.help_text:
                continue
            field.help_text = FIELD_HELP_TEXT.get(
                field.name,
                f'{candidate._meta.verbose_name}的{field.verbose_name}字段。',
            )
