# Generated by Django 4.2.30 on 2026-06-09 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('persona', models.CharField(max_length=120)),
                ('status', models.CharField(default='enabled', max_length=40)),
                ('tools', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('query', models.TextField()),
                ('severity', models.CharField(choices=[('info', '信息'), ('warning', '预警'), ('critical', '严重')], default='warning', max_length=32)),
                ('duration', models.CharField(default='5m', max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('annotations', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.CharField(max_length=80)),
                ('action', models.CharField(max_length=120)),
                ('resource', models.CharField(max_length=160)),
                ('ip_address', models.GenericIPAddressField(default='127.0.0.1')),
                ('detail', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('hostname', models.CharField(max_length=120)),
                ('ip_address', models.GenericIPAddressField()),
                ('environment', models.CharField(default='prod', max_length=40)),
                ('region', models.CharField(default='cn-east', max_length=80)),
                ('role', models.CharField(default='app', max_length=80)),
                ('owner', models.CharField(default='平台运维', max_length=80)),
                ('os', models.CharField(default='Ubuntu 22.04', max_length=120)),
                ('status', models.CharField(choices=[('healthy', '健康'), ('warning', '预警'), ('critical', '严重'), ('offline', '离线')], default='healthy', max_length=32)),
                ('cpu_usage', models.FloatField(default=0)),
                ('memory_usage', models.FloatField(default=0)),
                ('disk_usage', models.FloatField(default=0)),
                ('latency_ms', models.FloatField(default=0)),
                ('heartbeat_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tags', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('integration_type', models.CharField(choices=[('llm', 'LLM'), ('prometheus', 'Prometheus'), ('loki', 'Loki'), ('tempo', 'Tempo'), ('grafana', 'Grafana'), ('notification', '通知')], max_length=40)),
                ('provider', models.CharField(max_length=80)),
                ('endpoint', models.CharField(blank=True, max_length=240)),
                ('status', models.CharField(default='mock', max_length=40)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(default='诊断', max_length=80)),
                ('source', models.CharField(default='builtin', max_length=120)),
                ('content', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('region', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('report_type', models.CharField(default='incident', max_length=80)),
                ('summary', models.TextField()),
                ('content', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('category', models.CharField(default='诊断', max_length=80)),
                ('tool_class', models.CharField(default='safe', max_length=40)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('schema', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=120, unique=True)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TraceSpan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trace_id', models.CharField(max_length=80)),
                ('span_id', models.CharField(max_length=80)),
                ('service', models.CharField(max_length=120)),
                ('operation', models.CharField(max_length=160)),
                ('duration_ms', models.FloatField(default=0)),
                ('status', models.CharField(default='ok', max_length=40)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WebShellSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='mock', max_length=40)),
                ('opened_by', models.CharField(default='admin', max_length=80)),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shell_sessions', to='ops.device')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', '管理员'), ('sre', 'SRE'), ('viewer', '只读用户')], default='sre', max_length=32)),
                ('title', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='ops.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopologyNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('node_type', models.CharField(default='service', max_length=60)),
                ('status', models.CharField(default='healthy', max_length=40)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ops.device')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopologyEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation', models.CharField(default='depends_on', max_length=80)),
                ('latency_ms', models.FloatField(default=0)),
                ('error_rate', models.FloatField(default=0)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='ops.topologynode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='ops.topologynode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetricSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric', models.CharField(max_length=120)),
                ('value', models.FloatField()),
                ('unit', models.CharField(default='%', max_length=24)),
                ('sampled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='ops.device')),
            ],
            options={
                'ordering': ['-sampled_at'],
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.CharField(max_length=120)),
                ('severity', models.CharField(choices=[('info', '信息'), ('warning', '预警'), ('error', '错误'), ('critical', '严重')], default='info', max_length=32)),
                ('message', models.TextField()),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='ops.device')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('warning', '预警'), ('critical', '严重'), ('major', '重大')], default='warning', max_length=32)),
                ('status', models.CharField(choices=[('open', '处理中'), ('acknowledged', '已确认'), ('mitigated', '已缓解'), ('resolved', '已解决')], default='open', max_length=32)),
                ('summary', models.TextField(blank=True)),
                ('root_cause', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0)),
                ('timeline', models.JSONField(blank=True, default=list)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('assignee', models.CharField(blank=True, max_length=80)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='ops.device')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='ops.alertrule')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EdgeAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(default='0.8.4', max_length=40)),
                ('status', models.CharField(choices=[('online', '在线'), ('degraded', '降级'), ('offline', '离线')], default='online', max_length=32)),
                ('tunnel_id', models.CharField(blank=True, max_length=120)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edge', to='ops.device')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手'), ('tool', '工具')], max_length=32)),
                ('content', models.TextField()),
                ('tool_calls', models.JSONField(blank=True, default=list)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ops.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=80)),
                ('message', models.TextField()),
                ('actor', models.CharField(default='system', max_length=80)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ops.incident')),
            ],
            options={
                'ordering': ['occurred_at'],
            },
        ),
    ]
