# Generated by Django 4.2.30 on 2026-06-09 14:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_backupsnapshot_changeevent_cloudasset_knowledgerepo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('provider', models.CharField(choices=[('slack', 'Slack'), ('telegram', 'Telegram'), ('larksuite', '飞书'), ('dingtalk', '钉钉'), ('wecom', '企业微信'), ('webhook', 'Webhook')], max_length=40)),
                ('status', models.CharField(default='enabled', max_length=40)),
                ('inbound_url', models.CharField(blank=True, max_length=240)),
                ('outbound_url', models.CharField(blank=True, max_length=240)),
                ('default_agent', models.CharField(default='incident-investigator', max_length=80)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvestigationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('status', models.CharField(choices=[('queued', '排队中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败')], default='completed', max_length=32)),
                ('agent_key', models.CharField(default='incident-investigator', max_length=80)),
                ('coordinator_plan', models.JSONField(blank=True, default=list)),
                ('causal_graph', models.JSONField(blank=True, default=list)),
                ('blast_radius', models.JSONField(blank=True, default=dict)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('conclusion', models.TextField(blank=True)),
                ('source_refs', models.JSONField(blank=True, default=list)),
                ('suggested_actions', models.JSONField(blank=True, default=list)),
                ('confidence', models.FloatField(default=0)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigation_runs', to='ops.incident')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigation_runs', to='ops.chatsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelRoutePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('task_type', models.CharField(default='rca', max_length=80)),
                ('provider', models.CharField(default='OpenAI Compatible', max_length=80)),
                ('model', models.CharField(default='gpt-4.1-mini', max_length=120)),
                ('fallback_model', models.CharField(blank=True, max_length=120)),
                ('daily_token_limit', models.IntegerField(default=200000)),
                ('enabled', models.BooleanField(default=True)),
                ('rules', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToolCallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tool_name', models.CharField(max_length=120)),
                ('tool_class', models.CharField(choices=[('safe', '只读'), ('mutating', '变更'), ('dangerous', '高危')], default='safe', max_length=32)),
                ('specialist', models.CharField(default='incident-investigator', max_length=80)),
                ('input', models.JSONField(blank=True, default=dict)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('completed', '已完成'), ('blocked', '已拦截'), ('failed', '失败')], default='completed', max_length=32)),
                ('duration_ms', models.IntegerField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='ops.investigationrun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
