# Generated by Django 4.2.30 on 2026-06-09 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_chatchannel_investigationrun_modelroutepolicy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='ops.organization'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ops.organization'),
        ),
        migrations.AddField(
            model_name='backupsnapshot',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup_snapshots', to='ops.organization'),
        ),
        migrations.AddField(
            model_name='changeevent',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_events', to='ops.organization'),
        ),
        migrations.AddField(
            model_name='chatchannel',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_channels', to='ops.organization'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='ops.organization'),
        ),
        migrations.AddField(
            model_name='cloudasset',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cloud_assets', to='ops.organization'),
        ),
        migrations.AddField(
            model_name='device',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='ops.organization'),
        ),
        migrations.AddField(
            model_name='incident',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='ops.organization'),
        ),
        migrations.AddField(
            model_name='integration',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='ops.organization'),
        ),
        migrations.AddField(
            model_name='investigationrun',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigation_runs', to='ops.organization'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_documents', to='ops.organization'),
        ),
        migrations.AddField(
            model_name='knowledgerepo',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_repos', to='ops.organization'),
        ),
        migrations.AddField(
            model_name='maintenancewindow',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_windows', to='ops.organization'),
        ),
        migrations.AddField(
            model_name='modelroutepolicy',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_routes', to='ops.organization'),
        ),
        migrations.AddField(
            model_name='monitorpanel',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_panels', to='ops.organization'),
        ),
        migrations.AddField(
            model_name='mutatingproposal',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='ops.organization'),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to='ops.organization'),
        ),
        migrations.AddField(
            model_name='oncallschedule',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oncall_schedules', to='ops.organization'),
        ),
        migrations.AddField(
            model_name='playbook',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playbooks', to='ops.organization'),
        ),
        migrations.AddField(
            model_name='report',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='ops.organization'),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to='ops.organization'),
        ),
        migrations.AddField(
            model_name='slotarget',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slo_targets', to='ops.organization'),
        ),
        migrations.AddField(
            model_name='sshidentity',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ssh_identities', to='ops.organization'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='ops.organization'),
        ),
        migrations.AddField(
            model_name='topologynode',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topology_nodes', to='ops.organization'),
        ),
        migrations.AddField(
            model_name='watchtask',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_tasks', to='ops.organization'),
        ),
    ]
