# Generated by Django 4.2.30 on 2026-06-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0005_assign_existing_rows_to_default_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=32),
        ),
        migrations.AlterField(
            model_name='chatchannel',
            name='provider',
            field=models.CharField(choices=[('slack', 'Slack'), ('telegram', 'Telegram'), ('larksuite', 'LarkSuite'), ('dingtalk', 'DingTalk'), ('wecom', 'WeCom'), ('webhook', 'Webhook')], max_length=40),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], max_length=32),
        ),
        migrations.AlterField(
            model_name='device',
            name='owner',
            field=models.CharField(default='platform-ops', max_length=80),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('critical', 'Critical'), ('offline', 'Offline')], default='healthy', max_length=32),
        ),
        migrations.AlterField(
            model_name='edgeagent',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('degraded', 'Degraded'), ('offline', 'Offline')], default='online', max_length=32),
        ),
        migrations.AlterField(
            model_name='incident',
            name='severity',
            field=models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical'), ('major', 'Major')], default='warning', max_length=32),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('mitigated', 'Mitigated'), ('resolved', 'Resolved')], default='open', max_length=32),
        ),
        migrations.AlterField(
            model_name='integration',
            name='integration_type',
            field=models.CharField(choices=[('llm', 'LLM'), ('prometheus', 'Prometheus'), ('loki', 'Loki'), ('tempo', 'Tempo'), ('grafana', 'Grafana'), ('notification', 'Notification')], max_length=40),
        ),
        migrations.AlterField(
            model_name='investigationrun',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=32),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='category',
            field=models.CharField(default='Diagnostics', max_length=80),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=32),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(default='Diagnostics', max_length=80),
        ),
        migrations.AlterField(
            model_name='toolcallrecord',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('blocked', 'Blocked'), ('failed', 'Failed')], default='completed', max_length=32),
        ),
        migrations.AlterField(
            model_name='toolcallrecord',
            name='tool_class',
            field=models.CharField(choices=[('safe', 'Safe'), ('mutating', 'Mutating'), ('dangerous', 'Dangerous')], default='safe', max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('sre', 'SRE'), ('member', 'Member'), ('viewer', 'Viewer'), ('readonly', 'Readonly')], default='sre', max_length=32),
        ),
    ]
