# Generated by Django 4.2.30 on 2026-06-09 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0006_alter_alertrule_severity_alter_chatchannel_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopologyNodeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.SlugField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopologyRelationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.SlugField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='edgeagent',
            name='access_key',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='edgeagent',
            name='secret_key_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='edgeagent',
            name='secret_rotated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['organization', 'enabled'], name='ops_alertru_organiz_b77da1_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['organization', 'status'], name='ops_device_organiz_22ad97_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['organization', 'status'], name='ops_inciden_organiz_84952f_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['organization', 'severity'], name='ops_inciden_organiz_1867a0_idx'),
        ),
        migrations.AddIndex(
            model_name='metricsample',
            index=models.Index(fields=['metric', 'sampled_at'], name='ops_metrics_metric_b5e4e8_idx'),
        ),
        migrations.AddIndex(
            model_name='tracespan',
            index=models.Index(fields=['trace_id'], name='ops_tracesp_trace_i_6f8fad_idx'),
        ),
        migrations.AddIndex(
            model_name='tracespan',
            index=models.Index(fields=['service', 'started_at'], name='ops_tracesp_service_ee40a9_idx'),
        ),
    ]
