# Generated by Django 4.2.30 on 2026-06-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0009_role_and_dynamic_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
