# Generated by Django 4.2.30 on 2026-07-17 08:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0023_delete_model_route_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlmCallConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('system_prompt', models.TextField(blank=True)),
                ('user_prompt_template', models.TextField(blank=True)),
                ('output_format', models.CharField(choices=[('text', 'Text'), ('json', 'JSON')], default='text', max_length=16)),
                ('auth_mode', models.CharField(choices=[('internal', 'Internal'), ('token', 'Token'), ('both', 'Internal and Token')], default='internal', max_length=16)),
                ('status', models.CharField(choices=[('available', 'Available'), ('disabled', 'Disabled')], default='available', max_length=32)),
                ('temperature', models.FloatField(default=0.2)),
                ('max_output_tokens', models.PositiveIntegerField(default=2048)),
                ('token_prefix', models.CharField(blank=True, max_length=18)),
                ('token_hash', models.CharField(blank=True, max_length=128)),
                ('remark', models.TextField(blank=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_call_configs', to='ops.organization')),
            ],
            options={
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='LlmCallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.CharField(max_length=80, unique=True)),
                ('call_code', models.CharField(max_length=80)),
                ('actor', models.CharField(blank=True, max_length=80)),
                ('source', models.CharField(default='internal', max_length=40)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=32)),
                ('provider', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('latency_ms', models.FloatField(default=0)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('input_summary', models.TextField(blank=True)),
                ('output_content', models.TextField(blank=True)),
                ('output_json', models.JSONField(blank=True, null=True)),
                ('output_summary', models.TextField(blank=True)),
                ('attempts', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='ops.llmcallconfig')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_call_records', to='ops.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['call_code', 'status', 'created_at'], name='ops_llm_record_code_status_idx'), models.Index(fields=['actor', 'created_at'], name='ops_llm_record_actor_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='llmcallconfig',
            index=models.Index(fields=['code', 'status'], name='ops_llm_call_code_status_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcallconfig',
            index=models.Index(fields=['auth_mode', 'status'], name='ops_llm_call_auth_status_idx'),
        ),
    ]
