# Generated by Django 4.2.30 on 2026-07-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0024_llmcallconfig_llmcallrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmcallconfig',
            name='rate_limit_day',
            field=models.PositiveIntegerField(default=5000, help_text='统一入口每天最大调用次数，0 表示不限速。'),
        ),
        migrations.AddField(
            model_name='llmcallconfig',
            name='rate_limit_hour',
            field=models.PositiveIntegerField(default=200, help_text='统一入口每小时最大调用次数，0 表示不限速。'),
        ),
        migrations.AddField(
            model_name='llmcallconfig',
            name='rate_limit_minute',
            field=models.PositiveIntegerField(default=50, help_text='统一入口每分钟最大调用次数，0 表示不限速。'),
        ),
        migrations.AddField(
            model_name='llmcallconfig',
            name='rate_limit_second',
            field=models.PositiveIntegerField(default=20, help_text='统一入口每秒最大调用次数，0 表示不限速。'),
        ),
    ]
