# Generated by Codex on 2026-07-17

from django.db import migrations, models


def sync_config_status_from_latest_test(apps, schema_editor):
    LlmCallConfig = apps.get_model('ops', 'LlmCallConfig')
    LlmCallRecord = apps.get_model('ops', 'LlmCallRecord')
    for config in LlmCallConfig.objects.exclude(status='disabled'):
        latest_test = LlmCallRecord.objects.filter(config_id=config.id, source='test').order_by('-created_at', '-id').first()
        if not latest_test:
            continue
        next_status = 'available' if latest_test.status == 'success' else 'unavailable'
        if config.status != next_status:
            config.status = next_status
            config.save(update_fields=['status'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0025_llmcallconfig_rate_limit_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmcallconfig',
            name='status',
            field=models.CharField(
                choices=[
                    ('available', 'Available'),
                    ('unavailable', 'Unavailable'),
                    ('disabled', 'Disabled'),
                ],
                default='available',
                max_length=32,
            ),
        ),
        migrations.RunPython(sync_config_status_from_latest_test, noop_reverse),
    ]
