# Generated by Django 4.2.30 on 2026-07-17 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ops', '0028_aiassistant_session_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiAssistantAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_role', models.CharField(choices=[('user_upload', 'User Upload'), ('assistant_reply', 'Assistant Reply')], default='user_upload', max_length=32)),
                ('original_name', models.CharField(max_length=260)),
                ('file_name', models.CharField(max_length=260)),
                ('content_type', models.CharField(blank=True, max_length=160)),
                ('file_extension', models.CharField(blank=True, max_length=24)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('oss_bucket', models.CharField(blank=True, max_length=160)),
                ('oss_endpoint', models.CharField(blank=True, max_length=240)),
                ('oss_object_key', models.CharField(blank=True, max_length=520)),
                ('oss_url', models.URLField(blank=True, max_length=1000)),
                ('extracted_text', models.TextField(blank=True)),
                ('parse_status', models.CharField(choices=[('success', 'Success'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='success', max_length=32)),
                ('parse_error', models.TextField(blank=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='ops.aiassistantmessage')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_assistant_attachments', to='ops.organization')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ops.aiassistantsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_assistant_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='ops_ai_att_session_created_idx'), models.Index(fields=['message', 'created_at'], name='ops_ai_att_message_created_idx'), models.Index(fields=['user', 'created_at'], name='ops_ai_att_user_created_idx')],
            },
        ),
    ]
