# Generated by Django 4.2.30 on 2026-07-18 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ops', '0029_aiassistantattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiassistantmessage',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='AiUserMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_user_memories', to='ops.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_memory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'updated_at'], name='ops_ai_memory_org_updated_idx'), models.Index(fields=['user'], name='ops_ai_memory_user_idx')],
            },
        ),
    ]
