# Generated by Django 4.2.30 on 2026-07-23 17:03

import data_security.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def remove_legacy_llm_setting(apps, schema_editor):
    """Delete the unused LLM strategy setting after the old AI module is removed."""
    SystemSetting = apps.get_model('ops', 'SystemSetting')
    SystemSetting.objects.filter(key='config.llm_strategy.global').delete()


LEGACY_TABLES = (
    'ops_aiassistantattachment',
    'ops_aiassistantmessage',
    'ops_aiassistantmemory',
    'ops_aiassistantsession',
    'ops_aiusermemory',
    'ops_alertevent',
    'ops_investigationrun',
    'ops_incident',
    'ops_alertrule',
    'ops_chatmessage',
    'ops_chatsession',
    'ops_chatchannel',
    'ops_cvefinding',
    'ops_edgeagent',
    'ops_logentry',
    'ops_metricsample',
    'ops_topologyedge',
    'ops_topologynode',
    'ops_topologynodetype',
    'ops_topologyrelationtype',
    'ops_toolcallrecord',
    'ops_playbookrun',
    'ops_llmcallrecord',
    'ops_device',
    'ops_cloudasset',
    'ops_changeevent',
    'ops_knowledgedocument',
    'ops_knowledgerepo',
    'ops_llmcallconfig',
    'ops_maintenancewindow',
    'ops_marketplacepackage',
    'ops_monitorpanel',
    'ops_mutatingproposal',
    'ops_notificationchannel',
    'ops_oncallschedule',
    'ops_playbook',
    'ops_report',
    'ops_reportschedule',
    'ops_skill',
    'ops_sshidentity',
    'ops_tracespan',
    'ops_watchtask',
    'ops_agent',
)


def drop_legacy_tables(apps, schema_editor):
    """Drop empty tables from modules that are no longer part of the product."""
    connection = schema_editor.connection
    constraints_disabled = connection.disable_constraint_checking()
    try:
        for table_name in LEGACY_TABLES:
            quoted_name = schema_editor.quote_name(table_name)
            schema_editor.execute(f'DROP TABLE IF EXISTS {quoted_name}')
    finally:
        if constraints_disabled:
            connection.enable_constraint_checking()


class Migration(migrations.Migration):

    # SQLite cannot safely rebuild the old indexed AI tables one field at a
    # time. The migration therefore drops those verified-empty tables in one
    # database operation and applies the generated removals to state only.
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ops', '0033_database_permission_menu'),
    ]

    operations = [
        migrations.RunPython(remove_legacy_llm_setting, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.RemoveField(
            model_name='aiassistantattachment',
            name='message',
        ),
        migrations.RemoveField(
            model_name='aiassistantattachment',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='aiassistantattachment',
            name='session',
        ),
        migrations.RemoveField(
            model_name='aiassistantattachment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='aiassistantmessage',
            name='session',
        ),
        migrations.RemoveField(
            model_name='aiassistantsession',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='aiassistantsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='aiusermemory',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='aiusermemory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='alertevent',
            name='incident',
        ),
        migrations.RemoveField(
            model_name='alertrule',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='changeevent',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='chatchannel',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='session',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cloudasset',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='cvefinding',
            name='device',
        ),
        migrations.RemoveField(
            model_name='device',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='edgeagent',
            name='device',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='device',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='investigationrun',
            name='incident',
        ),
        migrations.RemoveField(
            model_name='investigationrun',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='investigationrun',
            name='session',
        ),
        migrations.RemoveField(
            model_name='knowledgedocument',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='knowledgerepo',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='llmcallconfig',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='llmcallrecord',
            name='config',
        ),
        migrations.RemoveField(
            model_name='llmcallrecord',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='device',
        ),
        migrations.RemoveField(
            model_name='maintenancewindow',
            name='organization',
        ),
        migrations.DeleteModel(
            name='MarketplacePackage',
        ),
        migrations.RemoveField(
            model_name='metricsample',
            name='device',
        ),
        migrations.RemoveField(
            model_name='monitorpanel',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='mutatingproposal',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='notificationchannel',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='oncallschedule',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='playbook',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='playbookrun',
            name='playbook',
        ),
        migrations.RemoveField(
            model_name='report',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='reportschedule',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.RemoveField(
            model_name='sshidentity',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='toolcallrecord',
            name='run',
        ),
        migrations.RemoveField(
            model_name='topologyedge',
            name='source',
        ),
        migrations.RemoveField(
            model_name='topologyedge',
            name='target',
        ),
        migrations.RemoveField(
            model_name='topologynode',
            name='device',
        ),
        migrations.RemoveField(
            model_name='topologynode',
            name='organization',
        ),
        migrations.DeleteModel(
            name='TopologyNodeType',
        ),
        migrations.DeleteModel(
            name='TopologyRelationType',
        ),
        migrations.DeleteModel(
            name='TraceSpan',
        ),
        migrations.RemoveField(
            model_name='watchtask',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='permissionmenuaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(help_text='具体业务操作代码。', max_length=120),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.CharField(help_text='执行操作的用户名。', max_length=80),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='记录创建时间。'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='detail',
            field=models.JSONField(blank=True, default=dict, help_text='用于生成友好详情的结构化操作上下文。'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.BigAutoField(auto_created=True, help_text='数据库主键。', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1', help_text='发起操作的客户端 IP 地址。'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='操作发生时用户所属的组织。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ops.organization'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='resource',
            field=models.CharField(help_text='被操作对象的用户友好标识。', max_length=160),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='记录最后更新时间。'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='记录创建时间。'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, help_text='组织或部门的用途说明。'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.BigAutoField(auto_created=True, help_text='数据库主键。', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True, help_text='组织是否可用。'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_default',
            field=models.BooleanField(default=False, help_text='是否为系统默认公司根节点。'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='组织或部门的显示名称。', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('company', '公司'), ('department', '部门')], default='department', help_text='节点类型：公司或部门。', max_length=32),
        ),
        migrations.AlterField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='上级组织；为空表示公司根节点。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='ops.organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='region',
            field=models.CharField(blank=True, help_text='组织所在区域。', max_length=80),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(help_text='组织的唯一英文标识，用于接口和令牌。', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='记录最后更新时间。'),
        ),
        migrations.AlterField(
            model_name='permissionmenuaction',
            name='code',
            field=models.CharField(help_text='页面内唯一的操作代码。', max_length=80),
        ),
        migrations.AlterField(
            model_name='permissionmenuaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='记录创建时间。'),
        ),
        migrations.AlterField(
            model_name='permissionmenuaction',
            name='id',
            field=models.BigAutoField(auto_created=True, help_text='数据库主键。', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='permissionmenuaction',
            name='is_active',
            field=models.BooleanField(default=True, help_text='操作权限是否启用。'),
        ),
        migrations.AlterField(
            model_name='permissionmenuaction',
            name='name',
            field=models.CharField(help_text='权限策略中展示的操作名称。', max_length=80),
        ),
        migrations.AlterField(
            model_name='permissionmenuaction',
            name='page',
            field=models.ForeignKey(help_text='操作所属的页面权限节点。', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='ops.permissionmenunode'),
        ),
        migrations.AlterField(
            model_name='permissionmenuaction',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='操作在权限策略中的展示顺序。'),
        ),
        migrations.AlterField(
            model_name='permissionmenuaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='记录最后更新时间。'),
        ),
        migrations.AlterField(
            model_name='permissionmenunode',
            name='aliases',
            field=models.JSONField(blank=True, default=list, help_text='共享此页面权限的前端路由别名。'),
        ),
        migrations.AlterField(
            model_name='permissionmenunode',
            name='code',
            field=models.CharField(help_text='菜单或页面的唯一权限代码。', max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='permissionmenunode',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='记录创建时间。'),
        ),
        migrations.AlterField(
            model_name='permissionmenunode',
            name='icon',
            field=models.CharField(blank=True, help_text='前端本地图标库中的图标名称。', max_length=80),
        ),
        migrations.AlterField(
            model_name='permissionmenunode',
            name='id',
            field=models.BigAutoField(auto_created=True, help_text='数据库主键。', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='permissionmenunode',
            name='is_active',
            field=models.BooleanField(default=True, help_text='菜单或页面权限是否启用。'),
        ),
        migrations.AlterField(
            model_name='permissionmenunode',
            name='name',
            field=models.CharField(help_text='菜单中展示的中文名称。', max_length=120),
        ),
        migrations.AlterField(
            model_name='permissionmenunode',
            name='node_type',
            field=models.CharField(choices=[('group', '菜单组'), ('page', '页面')], default='page', help_text='节点类型：菜单组或页面。', max_length=16),
        ),
        migrations.AlterField(
            model_name='permissionmenunode',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='上级菜单组；菜单组本身为空。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ops.permissionmenunode'),
        ),
        migrations.AlterField(
            model_name='permissionmenunode',
            name='path',
            field=models.CharField(blank=True, help_text='页面对应的前端路由。', max_length=240),
        ),
        migrations.AlterField(
            model_name='permissionmenunode',
            name='sidebar',
            field=models.BooleanField(default=True, help_text='是否在侧边栏展示。'),
        ),
        migrations.AlterField(
            model_name='permissionmenunode',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='同级菜单的展示顺序。'),
        ),
        migrations.AlterField(
            model_name='permissionmenunode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='记录最后更新时间。'),
        ),
        migrations.AlterField(
            model_name='permissionpolicy',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='记录创建时间。'),
        ),
        migrations.AlterField(
            model_name='permissionpolicy',
            name='department',
            field=models.ForeignKey(blank=True, help_text='授权对象为部门时关联的部门。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_permission_policies', to='ops.organization'),
        ),
        migrations.AlterField(
            model_name='permissionpolicy',
            name='id',
            field=models.BigAutoField(auto_created=True, help_text='数据库主键。', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='permissionpolicy',
            name='name',
            field=models.CharField(help_text='权限策略名称。', max_length=120),
        ),
        migrations.AlterField(
            model_name='permissionpolicy',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='策略所属的数据隔离组织。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_policies', to='ops.organization'),
        ),
        migrations.AlterField(
            model_name='permissionpolicy',
            name='priority',
            field=models.PositiveIntegerField(default=50, help_text='策略计算顺序，数值越小越先处理。'),
        ),
        migrations.AlterField(
            model_name='permissionpolicy',
            name='remark',
            field=models.TextField(blank=True, help_text='策略用途和变更原因备注。'),
        ),
        migrations.AlterField(
            model_name='permissionpolicy',
            name='status',
            field=models.CharField(choices=[('available', '可用'), ('disabled', '已禁用')], default='available', help_text='策略是否参与权限计算。', max_length=32),
        ),
        migrations.AlterField(
            model_name='permissionpolicy',
            name='subject_type',
            field=models.CharField(choices=[('department', '部门'), ('user', '用户')], help_text='授权对象类型：部门或用户。', max_length=32),
        ),
        migrations.AlterField(
            model_name='permissionpolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='记录最后更新时间。'),
        ),
        migrations.AlterField(
            model_name='permissionpolicy',
            name='user',
            field=models.ForeignKey(blank=True, help_text='授权对象为用户时关联的用户。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='permissionrule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='记录创建时间。'),
        ),
        migrations.AlterField(
            model_name='permissionrule',
            name='effect',
            field=models.CharField(choices=[('allow', '允许'), ('deny', '拒绝')], default='deny', help_text='授权效果；未明确允许时保持拒绝。', max_length=16),
        ),
        migrations.AlterField(
            model_name='permissionrule',
            name='id',
            field=models.BigAutoField(auto_created=True, help_text='数据库主键。', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='permissionrule',
            name='permission_code',
            field=models.CharField(help_text='数据库菜单目录中的完整权限代码。', max_length=160),
        ),
        migrations.AlterField(
            model_name='permissionrule',
            name='policy',
            field=models.ForeignKey(help_text='规则所属的权限策略。', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='ops.permissionpolicy'),
        ),
        migrations.AlterField(
            model_name='permissionrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='记录最后更新时间。'),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.SlugField(help_text='角色唯一代码，写入用户档案和令牌。', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='记录创建时间。'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, help_text='角色职责说明，不承载功能权限。'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.BigAutoField(auto_created=True, help_text='数据库主键。', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True, help_text='角色是否可分配给用户。'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_system',
            field=models.BooleanField(default=False, help_text='是否为不可删除的系统预置角色。'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='角色显示名称。', max_length=80),
        ),
        migrations.AlterField(
            model_name='role',
            name='rank',
            field=models.PositiveIntegerField(default=10, help_text='角色展示排序权重，数值越大越靠前。'),
        ),
        migrations.AlterField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='记录最后更新时间。'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='记录创建时间。'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='description',
            field=models.TextField(blank=True, help_text='设置项用途说明。'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='id',
            field=models.BigAutoField(auto_created=True, help_text='数据库主键。', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='key',
            field=models.CharField(help_text='设置项唯一键。', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='设置所属组织；为空表示平台级设置。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='ops.organization'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='记录最后更新时间。'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='value',
            field=data_security.fields.EncryptedJSONField(blank=True, default=dict, help_text='设置值；其中敏感字段使用 SM4 加密保存。'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='记录创建时间。'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, help_text='数据库主键。', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(help_text='用户当前所属部门。', on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='ops.organization'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=data_security.fields.EncryptedCharField(blank=True, help_text='使用 SM4 加密保存的手机号码。', max_length=512),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='sre', help_text='用户身份标签代码，不直接授予功能权限。', max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='title',
            field=models.CharField(blank=True, help_text='用户岗位或职务。', max_length=80),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='记录最后更新时间。'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(help_text='关联的登录用户。', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AiAssistantAttachment',
        ),
        migrations.DeleteModel(
            name='AiAssistantMessage',
        ),
        migrations.DeleteModel(
            name='AiAssistantSession',
        ),
        migrations.DeleteModel(
            name='AiUserMemory',
        ),
        migrations.DeleteModel(
            name='AlertEvent',
        ),
        migrations.DeleteModel(
            name='AlertRule',
        ),
        migrations.DeleteModel(
            name='ChangeEvent',
        ),
        migrations.DeleteModel(
            name='ChatChannel',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
        migrations.DeleteModel(
            name='CloudAsset',
        ),
        migrations.DeleteModel(
            name='CVEFinding',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='EdgeAgent',
        ),
        migrations.DeleteModel(
            name='Incident',
        ),
        migrations.DeleteModel(
            name='InvestigationRun',
        ),
        migrations.DeleteModel(
            name='KnowledgeDocument',
        ),
        migrations.DeleteModel(
            name='KnowledgeRepo',
        ),
        migrations.DeleteModel(
            name='LlmCallConfig',
        ),
        migrations.DeleteModel(
            name='LlmCallRecord',
        ),
        migrations.DeleteModel(
            name='LogEntry',
        ),
        migrations.DeleteModel(
            name='MaintenanceWindow',
        ),
        migrations.DeleteModel(
            name='MetricSample',
        ),
        migrations.DeleteModel(
            name='MonitorPanel',
        ),
        migrations.DeleteModel(
            name='MutatingProposal',
        ),
        migrations.DeleteModel(
            name='NotificationChannel',
        ),
        migrations.DeleteModel(
            name='OnCallSchedule',
        ),
        migrations.DeleteModel(
            name='Playbook',
        ),
        migrations.DeleteModel(
            name='PlaybookRun',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='ReportSchedule',
        ),
        migrations.DeleteModel(
            name='SSHIdentity',
        ),
        migrations.DeleteModel(
            name='ToolCallRecord',
        ),
        migrations.DeleteModel(
            name='TopologyEdge',
        ),
        migrations.DeleteModel(
            name='TopologyNode',
        ),
        migrations.DeleteModel(
            name='WatchTask',
        ),
    ]


LEGACY_MODEL_NAMES = {
    table_name.removeprefix('ops_') for table_name in LEGACY_TABLES
}
legacy_state_operations = []
core_operations = []
for operation in Migration.operations:
    model_name = getattr(operation, 'model_name', '').lower()
    deleted_name = getattr(operation, 'name', '').lower()
    is_legacy_operation = (
        model_name in LEGACY_MODEL_NAMES
        or (
            isinstance(operation, migrations.DeleteModel)
            and deleted_name in LEGACY_MODEL_NAMES
        )
    )
    if is_legacy_operation:
        legacy_state_operations.append(operation)
    else:
        core_operations.append(operation)

Migration.operations = [
    migrations.SeparateDatabaseAndState(
        database_operations=[
            migrations.RunPython(drop_legacy_tables, migrations.RunPython.noop),
        ],
        state_operations=legacy_state_operations,
    ),
    *core_operations,
]
