# Generated by Django 4.2.30 on 2026-07-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0048_ip_login_lock_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='otp_recovery_hashes',
        ),
    ]
