# Generated by Django 4.2.30 on 2026-07-24 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ops', '0049_remove_userprofile_otp_recovery_hashes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformLoginSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, help_text='数据库主键。', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='记录创建时间。')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新时间。')),
                ('session_id', models.CharField(help_text='登录会话的随机唯一标识。', max_length=64, unique=True)),
                ('auth_version', models.PositiveIntegerField(default=0, help_text='签发会话时的用户认证版本。')),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now, help_text='会话最近一次通过平台鉴权的时间。')),
                ('expires_at', models.DateTimeField(help_text='会话最晚有效时间。')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='用户退出或认证状态变更时的撤销时间。', null=True)),
                ('user', models.ForeignKey(help_text='当前登录会话关联的平台用户。', on_delete=django.db.models.deletion.CASCADE, related_name='platform_login_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['revoked_at', 'expires_at'], name='ops_login_active_idx'), models.Index(fields=['user', 'last_seen_at'], name='ops_login_user_seen_idx')],
            },
        ),
    ]
